import type { AppRole, Capability, NavItem } from "@/types/app";

export const APP_NAME = "R-Task Realty & Property Management Solutions";

export const PUBLIC_PATHS = [
  "/",
  "/about",
  "/services",
  "/contact",
  "/login",
  "/platform-login",
  "/reset-password",
  "/company/admin-setup",
];

export const ROLE_OPTIONS: Array<{ label: string; value: AppRole }> = [
  { label: "Corporate User", value: "corporate_user" },
  { label: "Employee", value: "employee" },
  { label: "Inspector", value: "inspector" },
  { label: "Super Admin", value: "super_admin" },
];

export const ROLE_CAPABILITIES: Record<AppRole, Capability[]> = {
  platform_admin: [
    "profile:view",
    "profile:manage",
  ],
  super_admin: [
    "dashboard:view",
    "history:view",
    "history:manage",
    "files:view",
    "files:upload",
    "files:approve",
    "files:delete",
    "files:download",
    "inspections:view",
    "inspections:create",
    "inspections:manage",
    "reports:view",
    "reports:create",
    "reports:manage",
    "evictions:view",
    "evictions:create",
    "evictions:manage",
    "support:view",
    "support:create",
    "profile:view",
    "profile:manage",
    "settings:view",
    "settings:manage",
    "properties:manage",
    "users:approve",
  ],
  corporate_user: [
    "dashboard:view",
    "history:view",
    "history:manage",
    "files:view",
    "files:upload",
    "files:approve",
    "files:delete",
    "files:download",
    "inspections:view",
    "inspections:create",
    "inspections:manage",
    "reports:view",
    "reports:create",
    "reports:manage",
    "evictions:view",
    "evictions:create",
    "evictions:manage",
    "support:view",
    "support:create",
    "profile:view",
    "profile:manage",
    "settings:view",
    "settings:manage",
    "properties:manage",
    "users:approve",
  ],
  employee: [
    "dashboard:view",
    "files:view",
    "files:upload",
    "files:download",
    "evictions:view",
    "evictions:create",
    "support:view",
    "support:create",
    "profile:view",
    "profile:manage",
  ],
  inspector: [
    "dashboard:view",
    "files:view",
    "files:upload",
    "files:download",
    "inspections:view",
    "inspections:create",
    "support:view",
    "support:create",
    "profile:view",
    "profile:manage",
  ],
};

export const APP_NAVIGATION: NavItem[] = [
  { href: "/dashboard", label: "Dashboard", capability: "dashboard:view" },
  { href: "/files", label: "Files", capability: "files:view" },
  { href: "/approvals", label: "Approvals", capability: "files:approve" },
  { href: "/inspections", label: "Inspections", capability: "inspections:view" },
  { href: "/shopping-reports", label: "Shopping Reports", capability: "reports:view" },
  { href: "/evictions", label: "Evictions", capability: "evictions:view" },
  { href: "/support", label: "Help & Support", capability: "support:view" },
  { href: "/profile", label: "Profile", capability: "profile:view" },
  { href: "/history", label: "History", capability: "history:view" },
  { href: "/settings", label: "Settings", capability: "settings:view" },
];
